# name: Swift

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v

# workflow 의 이름
name: Swift

on:
  # develop 브랜치에 push 나 pull request 이벤트가 일어났을때 해당 workflow 를 trigger
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# workflow의 실행은 하나 이상의 job으로 구성 됨
jobs:
  # 이 workflow 는 "build" 라는 single job 으로 구성
  build:
    # job이 실행될 환경 - 최신 mac os
    runs-on: macos-latest

    # Step은 job의 일부로 실행될 일련의 task들을 나타냄
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: |
        xcodebuild clean test -project ggwadang.xcodeproj/project.pbxproj -scheme ggwadang -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4'
      
